### ISSUE TITLE
Arduino library indexer not picking up new version

### ISSUE THREAD

**Issue by ubidefeo** [cygig/TimerEvent#2]
hi @cygig 
While setting up an example for my students I realised that the Arduino library indexer is still pulling the files with the `scr` folder name.
Could you please update the version number to `0.4.2` in `library.properties` and then create release `0.4.2`?
This will make sure that at the next scraping the working version of your library will be picked up and added to the index.

thank you 
u.

**Comment by cygig** [comment]
> hi @cygig
> While setting up an example for my students I realised that the Arduino library indexer is still pulling the files with the `scr` folder name.
> Could you please update the version number to `0.4.2` in `library.properties` and then create release `0.4.2`?
> This will make sure that at the next scraping the working version of your library will be picked up and added to the index.
> 
> thank you
> u.

I will take a look later on. So sorry, I am still a noob at GitHub.

**Comment by ubidefeo** [comment]
@cygig 
No worries, mate.
This has nothing to do with GitHub, it's just how our indexer works.
Besides... everyone's a noob at GitHub :D
thank you for replying so quickly
u.

**Comment by cygig** [comment]
Hello! I've updated to `version=0.4.2` under `library.properties` and released it under `v0.4.2`. Does that solve the issue? Do I have to make the version `0.4.2` without the 'v'?

Btw, what is indexer still pulling old files? Is it because I named it `0.41` instead of `0.4.1`?

**Comment by ubidefeo** [comment]
hi @cygig 
the library has been successfully pulled in by our indexer.
Yes, as you guessed the wrongly named version was part of the issue.
Essentially to update your lib you need to change the version in `library.properties` and create a new tag with the same version.
If you end up changing one of the two not at the same time the indexer will ignore the changes.

<img width="265" alt="Screenshot 2020-02-22 at 07 59 31" src="https://user-images.githubusercontent.com/1894487/75088143-a9ebd500-5549-11ea-9ac6-a3591890b035.png">

**Comment by cygig** [comment]
Sorry for the late reply. I get it now, I got a few more libraries to upload and I will be more careful from now on. 

Just wondering, you mentioned that you were teaching students, what kind of students are they? Here in Singapore, almost no one teaches Arduino for adults, most are holiday classes meant for teens.

**Comment by ubidefeo** [comment]
Thank you, @cygig 

I teach Physical Computing to Interaction Design students here in Europe during these two Masters in ID
- [CIID](http://ciid.dk/education/professional-programmes/)
- [MaInD](https://www.maind.supsi.ch)

This last course was an internal one at Arduino for our Visual Design Team and it was a lot of fun :)
