### ISSUE TITLE
Compile Error: 'TimerEvent' does not name a type, when Board = Arduino Nano 33 BLE

### ISSUE THREAD

**Issue by talee16** [cygig/TimerEvent#3]
When Board = "Arduino Nano 33 BLE" is selected, any usage of TimerEvent will cause compile error - 'TimerEvent' does not name a type.
 
By just changing whole library/file/class name from 'TimerEvent' to 'TimerEv', the mentioned error is gone.

**Comment by talee16** [comment]
There is another "TimerEvent.h" at path:
c:\Users(username)\AppData\Local\Arduino15\packages\arduino\hardware\mbed\1.3.2\cores\arduino\mbed\drivers\TimerEvent.h

The mbed core is installled when Board Manager added support of "Nano 33 BLE".
Reference: https://www.arduino.cc/en/Guide/NANO33BLESense

**Comment by cygig** [comment]
Ahh, sounds like it overlaps with another default class.
